alias h='history'
alias cp='cp -i'
alias mv='mv -i'
alias ls='ls -FC --color=always'
alias re='reset'
alias tr='tar zcvf'

alias des='cd /home/jordan/Desktop'
alias doc='cd /home/jordan/Documents'
alias dow='cd /home/jordan/Downloads'

alias p='cd /home/jordan/Desktop/2D_gaming'
alias p2='cd /home/jordan/Desktop/2D_gaming/jbjerke_proj2l'
alias p3='cd /home/jordan/Desktop/2D_gaming/jbjerke_proj3/tracker'
alias p4='cd /home/jordan/Desktop/2D_gaming/jbjerke_proj4/tracker'
alias p5='cd /home/jordan/Desktop/2D_gaming/jbjerke_proj5/tracker'
alias p6='cd /home/jordan/Desktop/2D_gaming/jbjerke_proj6/tracker'
alias 416='cd /home/jordan/Desktop/4160assets-2018'
alias pr='cd /home/jordan/Desktop/2D_gaming/prac_quiz/practice'
alias qu='cd /home/jordan/Desktop/2D_gaming/prac_quiz/quiz'

alias m='make'
alias mc='make clean'

alias r='./run'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
